version: '3.3'
services:
  tyk-dashboard:
    image: tykio/tyk-dashboard:latest
    environment:
    -        TYK_LOGLEVEL=debug
    -        TYK_INSTRUMENTATION=1
    ports:
    - "3000:3000"
    - "5000:5000"
    networks:
    - tyk
    depends_on:
    - tyk-redis
    - tyk-mongo
  tyk-gateway:
    image: tykio/tyk-gateway:latest
    ports:
    - "8080:8080"
    networks:
    - tyk
    depends_on:
    - tyk-redis
    environment:
    - TYK_INSTRUMENTATION=1
  tyk-pump:
    image: tykio/tyk-pump-docker-pub:latest
    networks:
    - tyk
    depends_on:
    - tyk-redis
    - tyk-mongo
    - tyk-gateway
  tyk-redis:
    image: redis
    ports:
    - "6379:6379"
    volumes:
    - redis-data:/data
    networks:
    - tyk
  tyk-mongo:
    image: mongo:3.2
    command: ["mongod", "--smallfiles"]
    ports:
    - "27017:27017"
    volumes:
    - mongo-data:/data/db
    networks:
    - tyk

volumes:
  redis-data:
  mongo-data:

networks:
  tyk:
